name: "Submit an issue"
description: Submit an issue with GrapheneOS
labels: ["new-issue"]
title: "Issue: [Issue title]"
body:
  - type: markdown
    attributes:
      value: |
        Submit an issue with GrapheneOS.
        Please discuss feature requests on the [official discussion forum](https://discuss.grapheneos.org).
  - type: dropdown
    id: is-issue
    attributes:
      label: This is an issue with GrapheneOS
      description: Use the forum for feature requests. If the issue is with Auditor or another service/app, please use the corresponding issue tracker.
      multiple: false
      options:
        - 'No'
        - 'Yes'
    validations:
        required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: |
        Please include any relevant logs. If the issue can be reproduced, list the steps on how to reproduce the issue here.
