name: "Issue Report"
description: File an issue with GrapheneOS
labels: ["new-issue"]
title: "[Issue]: "
body:
  - type: markdown
    attributes:
      value: |
        Please discuss feature requests on the [official discussion forum](https://discuss.grapheneos.org).
        If the issue is about another service or app, please file an issue with in the [corresponding issue tracker](https://grapheneos.org/contact#reporting-issues).
  - type: dropdown
    id: is-issue
    attributes:
      label: This is an issue with GrapheneOS
      multiple: false
      options:
        - 'No'
        - 'Yes'
    validations:
        required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: |
        Please include any relevant logs. If the issue can be reproduced, list the steps on how to reproduce the issue here.
    validations:
      required: true
